# Generated by Django 4.0.4 on 2022-05-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_orders_cod_orders_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
