# Generated by Django 3.0.14 on 2022-06-25 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productrating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='discounted_price',
            new_name='price',
        ),
    ]
