# Generated by Django 4.0.4 on 2022-04-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthDate',
            new_name='land_mark',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_line_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_line_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='flat_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pin_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
